#!/bin/sh

NAME=hbwired
ADDON_DIR=/usr/local/etc/config/addons/${NAME}
WWW_DIR=/usr/local/etc/config/addons/www/${NAME}
RCD_DIR=/usr/local/etc/config/rc.d

start()
{
  echo 'HBWired AddOn: Starting installation...'
  cd ${ADDON_DIR}
  ./installHBWired
  echo 'HBWired AddOn: Installation completed'
}

stop()
{
  echo 'HBWired AddOn: Nothing to stop (passive addon)'
}

uninstall()
{
  echo 'HBWired AddOn: Uninstalling...'

  mount -o remount,rw / 2>/dev/null

  # Restore fwmap backup
  if [ -f /firmware/fwmap.backup ]; then
    cp /firmware/fwmap.backup /firmware/fwmap
    rm -f /firmware/fwmap.backup
    echo 'Restored fwmap from backup'
  fi

  # Restore DEVDB.tcl backup
  if [ -f /www/config/devdescr/DEVDB.tcl.backup ]; then
    cp /www/config/devdescr/DEVDB.tcl.backup /www/config/devdescr/DEVDB.tcl
    rm -f /www/config/devdescr/DEVDB.tcl.backup
    echo 'Restored DEVDB.tcl from backup'
  fi

  # Remove XML files from hs485types
  rm -f /firmware/hs485types/hbw_*.xml
  rm -f /firmware/hs485types/hbw-*.xml
  rm -f /firmware/hs485types/HBW-*.xml

  # Remove device images
  rm -f /www/config/img/devices/250/HBW-*.png
  rm -f /www/config/img/devices/50/HBW-*_thumb.png

  # Remove translations from stringtable_de.txt
  STRINGTABLE="/www/config/stringtable_de.txt"
  if [ -f "$STRINGTABLE" ]; then
    sed -i '/^# HBWired AddOn/,/^$/d' "$STRINGTABLE"
  fi

  # Remove translations from translate.lang.stringtable.js
  TRANSLATE_JS="/www/webui/js/lang/de/translate.lang.stringtable.js"
  if [ -f "$TRANSLATE_JS" ]; then
    sed -i '/\/\/ HBWired AddOn/,/\/\/ END HBWired AddOn/d' "$TRANSLATE_JS"
  fi

  mount -o remount,ro / 2>/dev/null

  # Remove addon entry from hm_addons.cfg
  if [ -f /usr/local/etc/config/hm_addons.cfg ]; then
    grep -v "$NAME" /usr/local/etc/config/hm_addons.cfg > /tmp/hm_addons.cfg.tmp
    mv /tmp/hm_addons.cfg.tmp /usr/local/etc/config/hm_addons.cfg
  fi

  # Remove addon directories and rc.d entry
  rm -rf ${ADDON_DIR}
  rm -rf ${WWW_DIR}
  rm -f ${RCD_DIR}/${NAME}

  echo 'HBWired AddOn: Uninstallation completed'
  echo 'Please restart hs485d: /etc/init.d/S60hs485d restart'
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  uninstall)
    uninstall
    ;;
  restart)
    stop
    start
    ;;
  info)
    echo "Info: <b>HBWired AddOn</b><br>"
    echo "Info: Unterst&uuml;tzung f&uuml;r HomeBrewWired Ger&auml;te (Thorsten Pferdekaemper Library)"
    echo "Info: <a href='https://github.com/maxx3105/HBWired-AddOn' target='_blank'>HBWired-AddOn on GitHub</a>"
    echo "Version: $(cat ${ADDON_DIR}/VERSION 2>/dev/null || echo 'unknown')"
    echo "Name: HBWired AddOn"
    echo "Operations: uninstall restart"
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|uninstall|info}"
    exit 1
    ;;
esac

exit 0
