#!/bin/sh

ADDON_NAME=hbwired
RC_DIR=/usr/local/etc/config/rc.d
WWW_DIR=/usr/local/etc/config/addons/www/$ADDON_NAME
ADDON_DIR=/usr/local/etc/config/addons/$ADDON_NAME

# mount /usr/local if not already mounted
mount | grep /usr/local 2>&1 >/dev/null
if [ $? -eq 1 ]; then
  mount /usr/local
fi

# Startscript anlegen
cp -af rc.d/$ADDON_NAME ${RC_DIR}/
chmod +x ${RC_DIR}/$ADDON_NAME

# Web-Konfiguration anlegen
mkdir -p ${WWW_DIR}
cp -af www/* ${WWW_DIR}/
chmod 755 ${WWW_DIR}

# Addon-Verzeichnis anlegen
mkdir -p ${ADDON_DIR}
cp -af addon/* ${ADDON_DIR}/
chmod 755 ${ADDON_DIR}
chmod +x ${ADDON_DIR}/installHBWired

# Plattformspezifische Dateien kopieren
if [ "$1" = "CCU2" ]; then
  cp -af ccu2/* ${ADDON_DIR}/
elif [ "$1" = "CCU3" ]; then
  cp -af ccu3/* ${ADDON_DIR}/
elif [ "$1" = "HM-RASPBERRYMATIC" ]; then
  cp -af ccurm/* ${ADDON_DIR}/
else
  cp -af ccu3/* ${ADDON_DIR}/
fi
chmod +x ${ADDON_DIR}/update_addon

# WebUI-Button in hm_addons.cfg registrieren
${ADDON_DIR}/update_addon $ADDON_NAME

# Symbolic Links
rm -f ${WWW_DIR}/VERSION.txt
ln -sf ${ADDON_DIR}/VERSION ${WWW_DIR}/VERSION.txt
rm -f ${WWW_DIR}/addon
ln -sf ${ADDON_DIR} ${WWW_DIR}/addon

sync

exit 0
